app/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['username'], message: 'Es existiert bereits ein Benutzer mit diesem Benutzernamen')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $username = null;

    #[ORM\Column(type: Types::JSON)]
    private array $roles = [];

    /**
     * @var string|null The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(type: 'boolean')]
    private bool $isVerified = false;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $firstName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lastName = null;

    #[ORM\OneToMany(mappedBy: 'player', targetEntity: Bingo::class)]
    private Collection $bingos;

    public function __construct()
    {
        $this->bingos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @see UserInterface
     */
    public function getShortRoles(): array
    {
        return array_map(fn ($role) => str_replace('ROLE_', '', $role), $this->getRoles());
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function __toString(): string
    {
        return ucfirst($this->getUsername()) . $this->getFirstName() ? '(' . $this->getFirstName() . ')' : '';
    }

    /**
     * @return Collection<int, Bingo>
     */
    public function getBingos(): Collection
    {
        return $this->bingos;
    }

    public function addBingo(Bingo $bingo): self
    {
        if (!$this->bingos->contains($bingo)) {
            $this->bingos->add($bingo);
            $bingo->setPlayer($this);
        }

        return $this;
    }

    public function removeBingo(Bingo $bingo): self
    {
        if ($this->bingos->removeElement($bingo)) {
            // set the owning side to null (unless already changed)
            if ($bingo->getPlayer() === $this) {
                $bingo->setPlayer(null);
            }
        }

        return $this;
    }
}

app/src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('username')
            ->add('roles', CollectionType::class)
            ->add('email')
            ->add('isVerified')
            ->add('firstName')
            ->add('lastName')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

app/src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use App\Repository\WordleGameRepository;
use App\Repository\WordleGuessRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/profile', name: 'app_profile', methods: ['GET'])]
    public function profile(): Response
    {
        return $this->render('user/profile.html.twig', [
            'user' => $this->getUser(),
        ]);
    }

    #[Route('/{id}', name: 'app_user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/takeover', name: 'app_user_takeover', methods: ['GET'])]
    public function takeover(User $user): Response
    {

        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, UserRepository $userRepository): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->save($user, true);

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/delete', name: 'app_user_delete', methods: ['POST'])]
    public function delete(
        Request $request,
        User $user,
        UserRepository $userRepository,
        WordleGameRepository $gameRepository,
        WordleGuessRepository $guessRepository
    ): Response
    {
        foreach ($gameRepository->findBy(['player' => $user->getId()]) as $game) {
            foreach ($game->getGuesses() as $guess) {
                $guessRepository->remove($guess, true);
            }
            $gameRepository->remove($game, true);
        }

        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $userRepository->remove($user, true);
        }

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/change', name: 'app_user_change', methods: ['POST'])]
    public function change(Request $request, UserRepository $userRepository): Response
    {
        $user = $userRepository->find($request->get('user'));

        $username = $_POST['_username'];

        if ($username !== $user->getUsername() && $userRepository->findBy(['username' => $username])) {
            $this->addFlash('error', sprintf("Der Username '%s' existiert bereits, bitte wähle einen anderen...", $username));
        } elseif ($username !== $user->getUsername()) {
            $user->setUsername($username);
            $this->addFlash('success', sprintf("Dein Username wurde erfolgreich in '%s' geändert", $username));
        }

        $email = $_POST['_email'];
        if ($email !== $user->getEmail()) {
            $user->setEmail($email);
            $this->addFlash('success', sprintf("Deine Email wurde erfolgreich in '%s' geändert", $email));
        }

        $userRepository->save($user, true);


        return $this->redirectToRoute('app_profile');
    }

    #[Route('/change/password', name: 'app_user_change_password', methods: ['POST'])]
    public function changePassword(Request $request, UserRepository $userRepository, UserPasswordHasherInterface $userPasswordHashService): Response
    {
        $user = $userRepository->find($request->get('user'));
        $user->setPassword($userPasswordHashService->hashPassword($user, $_POST['_password1']));

        $userRepository->save($user, true);

        $this->addFlash('success', "Dein Password wurde erfolgreich geändert");

        return $this->render('user/profile.html.twig');
    }
}

app/templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

app/templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_user_index') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

app/templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Username</th>
                <th>Roles</th>
                <th>Email</th>
                <th>IsVerified</th>
                <th>FirstName</th>
                <th>LastName</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.roles ? user.shortRoles|join(', ')|lower : '' }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.isVerified ? 'Yes' : 'No' }}</td>
                <td>{{ user.firstName }}</td>
                <td>{{ user.lastName }}</td>
                <td class="text-end">
                    <a class="btn btn-small" href="{{ path('app_user_show', {'id': user.id}) }}">show</a>
                    <a class="btn btn-small" href="{{ path('app_user_edit', {'id': user.id}) }}">edit</a>
                    <a class="btn btn-small" href="{{ path('app_user_takeover', {'id': user.id}) }}">takeover</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn" href="{{ path('app_user_new') }}">Create new user</a>
{% endblock %}

app/templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('app_user_index') }}">back to list</a>
{% endblock %}

app/templates/user/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Register{% endblock %}

{% block headline %}Profil{% endblock %}

{% block body %}
    <div class="d-flex justify-content-center">
        <form action="{{ path('app_user_change', {'user': app.user.id}) }}" method="post">
            <h4 class="py-3">Nutzerdaten ändern:</h4>
            <div class="input-group overflow-hidden my-3">
                <label for="username"></label><span class="input-group-text">Nickname:</span>
                <input type="text" class="form-control" id="username" name="_username" aria-describedby="search" value="{{ app.user.username }}" min="5">
            </div>
            <div class="input-group overflow-hidden my-3">
                <label for="email"></label><span class="input-group-text">Email:</span>
                <input type="email" class="form-control" id="email" name="_email" aria-describedby="search" value="{{ app.user.email }}" min="5">
            </div>
            <div>
                <button class="input-group btn" type="submit">Ändern</button>
            </div>
        </form>
    </div>
    <div class="d-flex justify-content-center py-5">
        <form action="{{ path('app_user_change_password', {'user': app.user.id}) }}" method="post">
            <h4 class="pt-3">Passwort ändern:</h4>
            <div class="input-group overflow-hidden my-3">
                <label for="password1"></label><span class="input-group-text">Password:</span>
                <input type="password" class="form-control" id="password1" name="_password1" aria-describedby="search" value="">
            </div>
            <div class="input-group overflow-hidden my-3">
                <label for="password2"></label><span class="input-group-text">Bestätigung:</span>
                <input type="password" class="form-control" id="password2" name="_password2" aria-describedby="search" value="">
            </div>
            <div>
                <button id="submitPassword" class="input-group btn" type="submit" disabled>Ändern</button>
                <span>(Minimum 5 Zeichen)</span>
            </div>
        </form>
    </div>
    <div class="text-center">
        <div class="d-flex justify-content-center">
            <div class="mt-2"><a class="input-group btn px-5" href="{{ path('app_logout') }}">logout</a></div>
        </div>
    </div>
{% endblock %}

app/templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Username</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|join(', ') : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>IsVerified</th>
                <td>{{ user.isVerified ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>FirstName</th>
                <td>{{ user.firstName }}</td>
            </tr>
            <tr>
                <th>LastName</th>
                <td>{{ user.lastName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_user_index') }}">back to list</a>

    <a href="{{ path('app_user_edit', {'id': user.id}) }}">edit</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}