app/src/Entity/MovieList.php
<?php

namespace App\Entity;

use App\Repository\MovieListRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: MovieListRepository::class)]
class MovieList
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\ManyToMany(targetEntity: User::class)]
    #[ORM\JoinTable(name: 'movie_list_maintainer')]
    private Collection $maintainer;

    #[ORM\ManyToMany(targetEntity: User::class)]
    #[ORM\JoinTable(name: 'movie_list_subscriber')]
    private Collection $subscriber;

    #[ORM\OneToMany(mappedBy: 'movieList', targetEntity: MovieListEntry::class, orphanRemoval: true)]
    private Collection $movies;


    public function __construct()
    {
        $this->maintainer = new ArrayCollection();
        $this->subscriber = new ArrayCollection();
        $this->movies = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, UserInterface>
     */
    public function getMaintainer(): Collection
    {
        return $this->maintainer;
    }

    public function getMaintainerToString(User $currentUser): array
    {
        return array_map(fn (User $user) => $user === $currentUser ? 'Du' : ucfirst($user->getUsername()), $this->maintainer->toArray());
    }

    public function addMaintainer(UserInterface $maintainer): self
    {
        if (!$this->maintainer->contains($maintainer)) {
            $this->maintainer->add($maintainer);
        }

        return $this;
    }

    public function removeMaintainer(UserInterface $maintainer): self
    {
        $this->maintainer->removeElement($maintainer);

        return $this;
    }

    /**
     * @return Collection<int, UserInterface>
     */
    public function getSubscriber(): Collection
    {
        return $this->subscriber;
    }

    public function getSubscriberToString(User $currentUser): array
    {
        return array_map(fn (User $user) => $user === $currentUser ? 'Du' : ucfirst($user->getUsername()), $this->maintainer->toArray());
    }

    public function addSubscriber(UserInterface $subscriber): self
    {
        if (!$this->subscriber->contains($subscriber)) {
            $this->subscriber->add($subscriber);
        }

        return $this;
    }

    public function removeSubscriber(UserInterface $subscriber): self
    {
        $this->subscriber->removeElement($subscriber);

        return $this;
    }

    /**
     * @return Collection<int, MovieListEntry>
     */
    public function getMovies(): Collection
    {
        return $this->movies;
    }

    public function addMovie(MovieListEntry $movie): self
    {
        if (!$this->movies->contains($movie)) {
            $this->movies->add($movie);
            $movie->setMovieList($this);
        }

        return $this;
    }

    public function removeMovie(MovieListEntry $movie): self
    {
        if ($this->movies->removeElement($movie)) {
            // set the owning side to null (unless already changed)
            if ($movie->getMovieList() === $this) {
                $movie->setMovieList(null);
            }
        }

        return $this;
    }

    public function getUnwatchedMovies(): Collection
    {
        return $this->movies->filter(fn (MovieListEntry $movie) => !$movie->getTimeWatched());
    }

    public function getWatchedMovies(): Collection
    {
        return $this->movies->filter(fn (MovieListEntry $movie) => $movie->getTimeWatched());
    }

    public function __toString(): string
    {
        return $this->name;
    }
}

app/src/Form/MovieListType.php
<?php

namespace App\Form;

use App\Entity\MovieList;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MovieListType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => MovieList::class,
        ]);
    }
}

app/src/Controller/MovieListController.php
<?php

namespace App\Controller;

use App\Entity\Movie;
use App\Entity\MovieList;
use App\Entity\MovieListEntry;
use App\Form\MovieListType;
use App\Repository\MovieListEntryRepository;
use App\Repository\MovieListRepository;
use App\Repository\MovieRepository;
use App\Service\GoogleService;
use App\Service\LoggerService;
use DateTime;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/watchlist')]
class MovieListController extends AbstractController
{
    public function __construct(
        private readonly MovieRepository          $movieRepository,
        private readonly MovieListRepository      $listRepository,
        private readonly MovieListEntryRepository $entryRepository,
    )
    {
    }

    #[Route('/', name: 'app_movie_list_index', methods: ['GET'])]
    public function index(MovieListRepository $movieListRepository): Response
    {
        return $this->render('movie_list/index.html.twig', [
            'maintainedMovieLists' => $movieListRepository->findByMaintainer($this->getUser()),
            'subscribedMovieLists' => $movieListRepository->findBySubscriber($this->getUser()),
        ]);
    }

    #[Route('/new', name: 'app_movie_list_new', methods: ['GET', 'POST'])]
    public function new(Request $request, MovieListRepository $movieListRepository): Response
    {
        $movieList = new MovieList();
        $form = $this->createForm(MovieListType::class, $movieList);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $movieList->addMaintainer($this->getUser());
            $movieListRepository->save($movieList, true);

            return $this->redirectToRoute('app_movie_list_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('movie_list/new.html.twig', [
            'movieList' => $movieList,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/list', name: 'app_movie_list', methods: ['GET'])]
    public function list(MovieList $movieList): Response
    {
        return $this->render('movie_list/list.html.twig', [
            'movieList' => $movieList,
            'movieListEntries' => $this->entryRepository->findByCustomOrder($movieList),
        ]);
    }

    #[Route('/{id}/show', name: 'app_movie_list_show', methods: ['GET'])]
    public function show(MovieList $movieList): Response
    {
        return $this->render('movie_list/show.html.twig', [
            'movieList' => $movieList,
        ]);
    }

    #[Route('/{id}/movie/add', name: 'app_movie_list_movie_add', methods: ['POST'])]
    public function addEntry(MovieList $movieList, Request $request, GoogleService $googleService): Response
    {
        if (!in_array($this->getUser(), $movieList->getMaintainer()->toArray())) {
            $this->addFlash('error', 'Du bist nicht berechtigt, diese Liste zu bearbeiten');
            return $this->redirectToRoute('app_home');
        }

        $parameters = json_decode($request->getContent(), true);
        $movieListEntry = new MovieListEntry();
        $movieListEntry->setMovieList($movieList);

        if (!$movie = $this->movieRepository->findOneBy(['imdbId' => $parameters['id']])) {
            try {
                $movie = new Movie();
                $movie->setName($parameters['name']);
                $movie->setImdbId($parameters['id']);
                $movie->setYear($parameters['year']);
                $movie->setPosterUrl($parameters['posterUrl']);
                $movie->setGenre(explode(',', $parameters['genres']));

                $youtubeId = $googleService->getBestSearchResult($movie->getName(), $movie->getYear());
                if (str_contains($youtubeId, '&')) {
                    $youtubeId = substr($youtubeId, 0, strpos($youtubeId, '&'));
                }
                $movie->setTrailerYoutubeId($youtubeId);

                $this->movieRepository->save($movie, true);

            } catch (\Exception $e) {
                $this->addFlash('error', sprintf('Error: %s', $e->getMessage()));
                LoggerService::log('movie', sprintf('Error: %s', $e->getMessage()));
                return $this->redirectToRoute('app_movie_list', ['id' => $movieList->getId()]);
            }
        }

        $movieListEntry->setMovie($movie);
        $movieListEntry->setMovieList($movieList);
        $movieListEntry->setTimeAdded(new DateTime());
        $movieListEntry->setAddedBy($this->getUser());
        $this->entryRepository->save($movieListEntry, true);

        $this->addFlash('success', sprintf('Yesssss, "%s" merke ich mir :)', $movie->getName()));

        return $this->redirectToRoute('app_movie_list', ['id' => $movieList->getId()]);
    }

    #[Route('movie/{id}/delete', name: 'app_movie_list_movie_delete', methods: ['GET'])]
    public function deleteEntry(MovieListEntry $entry): Response
    {
        if (!in_array($this->getUser(), $entry->getMovieList()->getMaintainer()->toArray())) {
            $this->addFlash('error', 'Nice try, aber du bist nicht berechtigt, diesen Eintrag zu löschen ;)');
            return $this->redirectToRoute('app_home');
        }

        $this->entryRepository->remove($entry, true);
        $this->addFlash('success', sprintf('Der Eintrag "%s" wurde aus der Liste entfernt', $entry->getMovie()->getName()));

        return $this->redirectToRoute('app_movie_list', ['id' => $entry->getMovieList()->getId()]);
    }

    #[Route('/{id}/invite-maintainer', name: 'app_movie_list_invite_maintainer', methods: ['GET'])]
    public function inviteMaintainer(MovieList $movieList): Response
    {
        if (!in_array($this->getUser(), $movieList->getMaintainer()->toArray())) {
            $this->addFlash('error', 'Du bist nicht berechtigt, diese Liste zu bearbeiten');
            return $this->redirectToRoute('app_home');
        }

        return $this->render('movie_list/invite_maintainer.html.twig', [
            'movieList' => $movieList,
        ]);
    }

    #[Route('/{id}/invite-subscriber', name: 'app_movie_list_invite_subscriber', methods: ['GET'])]
    public function inviteSubscriber(MovieList $movieList): Response
    {
        if (!in_array($this->getUser(), $movieList->getMaintainer()->toArray())) {
            $this->addFlash('error', 'Du bist nicht berechtigt, diese Liste zu bearbeiten');
            return $this->redirectToRoute('app_home');
        }

        return $this->render('movie_list/invite_subscriber.html.twig', [
            'movieList' => $movieList,
        ]);
    }

    #[Route('/movie/set-as-watched', name: 'app_movie_list_movie_set_watched', methods: ['POST'])]
    public function setAsWatched(Request $request): Response
    {
        $entry = $this->entryRepository->find($request->get('id'));

        if (!in_array($this->getUser(), $entry->getMovieList()->getMaintainer()->toArray())) {
            $this->addFlash('error', 'Du bist nicht berechtigt, diese Liste zu bearbeiten');
            return $this->redirectToRoute('app_home');
        }

        try {
            $entry->setTimeWatched(new DateTime($request->get('date')));
            $this->entryRepository->save($entry, true);
            $this->addFlash('success', sprintf('Genial, "%s" wurde am %s angeschaut.', $entry->getMovie()->getName(), $request->get('date')));
        } catch (Exception $e) {
            $this->addFlash('error', sprintf('Irgendwas klappt mit "%s" nicht, versuch\'s nach dem Prinzip "23.03.2022" x)', $request->get('date')));
        }

        return $this->redirectToRoute('app_movie_list', ['id' => $entry->getMovieList()->getId()]);
    }

    #[Route('/{id}/edit', name: 'app_movie_list_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, MovieList $movieList): Response
    {
        if (!in_array($this->getUser(), $movieList->getMaintainer()->toArray())) {
            $this->addFlash('error', 'Du bist nicht berechtigt, diese Liste zu bearbeiten');
            return $this->redirectToRoute('app_home');
        }

        $form = $this->createForm(MovieListType::class, $movieList);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->listRepository->save($movieList, true);

            return $this->redirectToRoute('app_movie_list_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('movie_list/edit.html.twig', [
            'movieList' => $movieList,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_movie_list_delete', methods: ['POST'])]
    public function delete(Request $request, MovieList $movieList): Response
    {
        if (!in_array($this->getUser(), $movieList->getMaintainer()->toArray())) {
            $this->addFlash('error', 'Ziemlich ugly, aber du bist nicht berechtigt, diese Liste zu löschen ;)');
            return $this->redirectToRoute('app_home');
        }

        if ($this->isCsrfTokenValid('delete' . $movieList->getId(), $request->request->get('_token'))) {
            $this->listRepository->remove($movieList, true);
        }

        return $this->redirectToRoute('app_movie_list_index', [], Response::HTTP_SEE_OTHER);
    }
}

app/templates/movie_list/_delete_form.html.twig
<form method="post" action="{{ path('app_movie_list_delete', {'id': movieList.id}) }}"
      onsubmit="return confirm('Willst du wirklich die gesamte Liste löschen?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ movieList.id) }}">
    <button class="btn btn-small btn-plain">Liste löschen</button>
</form>

app/templates/movie_list/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit MovieList{% endblock %}

{% block body %}
    <h1>Edit MovieList</h1>

    {{ include('movie_list/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_movie_list_index') }}">back to list</a>

    {{ include('movie_list/_delete_form.html.twig') }}
{% endblock %}

app/templates/movie_list/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Watchlist{% endblock %}
{% block headline %}Deine Watchlisten{% endblock %}

{% block body %}
    <div class="row text-center justify-content-md-center">
        {% for movieList in maintainedMovieLists %}
            <div class="col-12 col-md-6 col-xl-4 mb-4">
                <a href="{{ path('app_movie_list', {'id': movieList.id}) }}">
                    <div class="card border-primary mx-auto w-75">
                        <div class="card-header h5">{{ movieList.name }}</div>
                        <div class="card-body text-primary">
                            <div class="text-dark">Filme & Serien:</div>
                            <div class="card-text">
                                <span class="fw-bold">{{ movieList.movies|length }}</span> Einträge, davon
                            </div>
                            <div class="card-text">
                                <span class="fw-bold">{{ movieList.unwatchedMovies|length }}</span> noch nicht geschaut
                            </div>
                            <div class="text-dark">Maintainer:</div>
                            <div class="card-text" style="">
                                <span>{{ movieList.maintainerToString(app.user)|join(', ', ' und ') }}</span>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}

        {% for movieList in subscribedMovieLists %}
            <div class="col-12 col-md-6 col-xl-4 mb-4">
                <a href="{{ path('app_movie_list', {'id': movieList.id}) }}">
                    <div class="card border-primary mx-auto w-75">
                        <div class="card-header h5">{{ movieList.name }}</div>
                        <div class="card-body text-primary">
                            <div class="text-dark">Filme & Serien:</div>
                            <div class="card-text">
                                <span class="fw-bold">{{ movieList.movies|length }}</span> Einträge, davon
                            </div>
                            <div class="card-text">
                                <span class="fw-bold">{{ movieList.unwatchedMovies|length }}</span> noch nicht geschaut
                            </div>
                            <div class="text-dark">Maintainer:</div>
                            <div class="card-text" style="">
                                <span>{{ movieList.maintainerToString(app.user)|join(', ', ' und ') }}</span>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}

        <div class="col-12"></div>
        <div class="col-12 col-md-6 col-xl-4 my-5">
            <a href="{{ path('app_movie_list_new') }}">
                <div class="card card-secondary border-primary mx-auto w-75">
                    <div class="card-header h5">Neu</div>
                    <div class="card-body text-primary">
                        <div class="text-dark font-italic">Erstelle eine neue Liste...</div>
                    </div>
                </div>
            </a>
        </div>
    </div>
{% endblock %}

app/templates/movie_list/invite_maintainer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Invite{% endblock %}
{% block headline %}Maintainer einladen{% endblock %}

{% block body %}
    <div class="d-flex justify-content-center text-center">
        <h4>
            Folgt ...
        </h4>
    </div>
    <div class="d-none d-flex justify-content-center text-center">
        <div class="col-6">
            <div>Schicke diesen Link an deine Freunde:</div>
            <div id="copyOnClick">
                <div class="input-group overflow-hidden my-3">
                    <label for="inviteUrl"></label>
                    <span id="copyMe" class="input-group-text" style="cursor: pointer; width: 90px">copy me!</span>
                    <input type="text" id="inviteUrl" name="inviteUrl" class="form-control" readonly
                           style="cursor: pointer"
                           value="{{ url('app_movie_list_invite_maintainer', {'id': movieList.id}) }}">
                </div>
            </div>
            <div class="fw-bold">Achtung!</div>
            <div>Maintainer können Filme und die ganze Liste löschen.</div>
            <div>
                Subscriber hingegen können die Liste nur anschauen:
            </div>
            <div>
                <a class="btn btn-small" href="{{ url('app_movie_list_invite_subscriber', {'id': movieList.id}) }}">
                    invite subscriber
                </a>
            </div>
        </div>
    </div>

    <script>
        let timeoutId = null;
        let copyText = document.getElementById('inviteUrl');
        let copyOnClick = document.getElementById('copyOnClick');
        copyOnClick.addEventListener('click', copyToClipboard);

        function copyToClipboard() {
            console.log(timeoutId)
            if (timeoutId !== null) return

            navigator.clipboard.writeText(copyText.value)
                .then(() => {
                    document.getElementById('copyMe').innerText = 'copied!';
                    timeoutId = setTimeout(() => {
                        document.getElementById('copyMe').innerText = 'copy me!';
                        timeoutId = null;
                    }, 1000);
                })
                .catch(err => {
                    console.log('Something went wrong', err);
                });
        }
    </script>
{% endblock %}

app/templates/movie_list/invite_subscriber.html.twig
{% extends 'base.html.twig' %}

{% block title %}Invite{% endblock %}
{% block headline %}Subscriber einladen{% endblock %}

{% block body %}
    <div class="d-flex justify-content-center text-center">
        <h4>
            Folgt ...
        </h4>
    </div>
    <div class="d-none d-flex justify-content-center text-center">
        <div class="col-6">
            <div>Schicke diesen Link an deine Freunde:</div>
            <div id="copyOnClick">
                <div class="input-group overflow-hidden my-3">
                    <label for="inviteUrl"></label>
                    <span id="copyMe" class="input-group-text" style="cursor: pointer; width: 90px">copy me!</span>
                    <input type="text" id="inviteUrl" name="inviteUrl" class="form-control" readonly
                           style="cursor: pointer"
                           value="{{ url('app_movie_list_invite_subscriber', {'id': movieList.id}) }}">
                </div>
            </div>
            <div>Subscriber können lediglich die Liste anschauen.</div>
            <div>
                Sollen auch Filme hinzugefügt werden können, dann lade einen Maintainer ein:
            </div>
            <div>
                <a class="btn btn-small" href="{{ url('app_movie_list_invite_maintainer', {'id': movieList.id}) }}">
                    invite maintainer
                </a>
            </div>
        </div>
    </div>

    <script>
        let timeoutId = null;
        let copyText = document.getElementById('inviteUrl');
        let copyOnClick = document.getElementById('copyOnClick');
        copyOnClick.addEventListener('click', copyToClipboard);

        function copyToClipboard() {
            console.log(timeoutId)
            if (timeoutId !== null) return

            navigator.clipboard.writeText(copyText.value)
                .then(() => {
                    document.getElementById('copyMe').innerText = 'copied!';
                    timeoutId = setTimeout(() => {
                        document.getElementById('copyMe').innerText = 'copy me!';
                        timeoutId = null;
                    }, 1000);
                })
                .catch(err => {
                    console.log('Something went wrong', err);
                });
        }
    </script>
{% endblock %}

app/templates/movie_list/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Watchlist{% endblock %}
{% block headline %}{{ movieList.name }}{% endblock %}

{% block body %}
    <div class="search-bar row mb-3">
        <div class="col-6 col-sm-9 col-md-6">
            <div class="d-flex justify-content-between">
                <div class="input-group bg-dark overflow-hidden">
                    <label for="imdb-search"></label><span class="input-group-text" id="search">Film/Serie hinzufügen:</span>
                    <input type="text" class="form-control" id="imdb-search" aria-describedby="search">
                </div>
            </div>
            <div class="search-results w-auto d-none" id="search_results"
                 data-url="{{ path('app_movie_list_movie_add', {'id': movieList.id}) }}"></div>
        </div>
        <div class="col-6 text-end d-flex justify-content-end align-items-center">
            <div class="mx-1">
                <a class="btn btn-small" href="{{ path('app_movie_list_invite_maintainer', {'id': movieList.id}) }}">
                    Maintainer hinzufügen
                </a>
                <a class="btn btn-small" href="{{ path('app_movie_list_invite_subscriber', {'id': movieList.id}) }}">
                    Subscriber hinzufügen
                </a>
            </div>
            <div>
                {{ include('movie_list/_delete_form.html.twig') }}
            </div>
        </div>
    </div>

    <div class="row mb-5">
        <div class="col">
            <table class="sortableTable filterableTable" id="movieList">
                <thead>
                <tr>
                    <th class="numericSort d-none d-lg-table-cell py-1" scope="col">
                        <label><input class="table-input input-sm text-center" size="2" placeholder="Jahr"></label>
                    </th>
                    <th class="py-1 alphanumericSort" scope="col">
                        <label><input class="table-input input-sm" placeholder="Name"></label>
                    </th>
                    <th class="py-1 alphanumericSort d-none d-lg-table-cell" scope="col">
                        <label><input class="table-input input-sm" placeholder="Genre"></label>
                    </th>
                    <th class="py-1 text-center d-none d-lg-grid" scope="col">Trailer</th>
                    <th class="py-1 text-center d-lg-none" scope="col">YT</th>
                    <th class="py-1 text-center" scope="col">Verfügbarkeit</th>
                    <th class="py-1 d-none d-lg-table-cell" scope="col">Geschaut?</th>
                    <th class="py-1 d-none d-lg-table-cell" scope="col">
                        <a class="edit-table" id="editTable">✎</a>
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for movieListEntry in movieListEntries %}
                    <tr class="{% if movieListEntry.timeWatched %}watchedRow{% endif %}">
                        <td class="d-none d-lg-table-cell text-center">{{ movieListEntry.movie.year }}</td>
                        <td class="fw-bold">
                            {{ movieListEntry.movie.name }}
                            {% if movieListEntry.timeAdded|date("U") > "-5 minutes"|date("U") %}<span
                                    class="newEntry">NEU</span>{% endif %}
                        </td>
                        <td class="d-none d-lg-table-cell">{{ movieListEntry.movie.genre|join(', ') }}</td>
                        <td class="text-center">
                            <a class="youtube-link text-white" href="https://www.youtube.com/watch?v={{ movieListEntry.movie.trailerYoutubeId }}"
                               target="_blank">↗</a>
                        </td>
                        <td class="text-center text-nowrap">
                            {% for provider in ['netflix', 'disney', 'amazon', 'youtube', 'wow', 'paramount'] %}
                                {% set str = 'inactive' %}{% if provider in movieListEntry.movie.streamProvider %}{% set str = 'active' %}{% endif %}
                                <a href="{{ path('app_movie_list_toggle_provider', {'id': movieListEntry.id, 'provider': provider}) }}">
                                    <img class="streamProvider {{ str }} mx-lg-1"
                                         src="{{ asset('img/%s.ico'|format(provider)) }}" alt="{{ provider }}">
                                </a>
                            {% endfor %}
                        </td>
                        <td class="d-none d-lg-table-cell">
                            {% if movieListEntry.timeWatched %}
                                <div class="toggleOnEdit">{{ movieListEntry.timeWatched|date('d.m.Y') }}</div>
                            {% else %}
                                <div class="toggleOnEdit">nope</div>
                            {% endif %}
                            <div class="d-none toggleOnEdit">
                                <form class="row" method="post" action="{{ path('app_movie_list_movie_set_watched', {'id': movieListEntry.id}) }}">
                                    <div class="col-10 p-0">
                                        <label for="date" class="d-none"></label>
                                        <input id="date" name="date" formmethod="post"
                                               value="{{ movieListEntry.timeWatched|date('d.m.Y') }}">
                                    </div>
                                    <div class="col-2 p-0">
                                        <button type="submit">OK</button>
                                    </div>
                                </form>
                            </div>
                        </td>
                        <td class="d-none d-lg-table-cell">
                            <a class="d-none removeMovie toggleOnEdit text-center"
                               href="{{ path('app_movie_list_movie_delete', {'id': movieListEntry.id}) }}">
                                <img class="delete" src="{{ asset('img/delete.png') }}" width="20" height="20"
                                     alt="removeMovie">
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

app/templates/movie_list/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Neue Watchlist{% endblock %}
{% block headline %}Neue Watchlist erstellen{% endblock %}

{% block body %}
    <div class="d-flex justify-content-center">
        {{ include('movie_list/_form.html.twig') }}
    </div>
{% endblock %}

app/templates/movie_list/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}MovieList{% endblock %}

{% block body %}
    <h1>MovieList</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ movieList.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ movieList.name }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_movie_list_index') }}">back to list</a>

    <a href="{{ path('app_movie_list_edit', {'id': movieList.id}) }}">edit</a>

    {{ include('movie_list/_delete_form.html.twig') }}
{% endblock %}